- name: Create Hive Database
  ansible.builtin.shell: |
    {{ mysql_install_dir }}/bin/mysql -u {{ mysql_hadoop_account }} --password={{ mysql_hadoop_account_password }} -e "
    DROP DATABASE IF EXISTS hive;
    CREATE DATABASE hive;"
  when: inventory_hostname == groups['hive'][0]

- name: Grant Mysql User for hadoop
  ansible.builtin.command:
    cmd: >
      {{ mysql_install_dir }}/bin/mysql -u root --password={{ mysql_root_password_new }} -e "GRANT ALL PRIVILEGES ON *.* TO '{{ mysql_hadoop_account }}'@'%'; FLUSH PRIVILEGES;"
  when: inventory_hostname == groups['mysql'][0]
