- name: Create Zookeeper Work Dir
  include_tasks: ../../common/tasks/create_dirs.yml
  vars:  
    create_dirs:
      - "{{ zookeeper_install_dir }}"
      - "{{ zookeeper_data_dir }}"
      - "{{ zookeeper_logs_dir }}"
      - "{{ zookeeper_log_dir }}"

- name: Upload Zookeeper tar.gz file
  include_tasks: ../../common/tasks/upload_files.yml
  vars:
    upload_files:
      - { src: 'files/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz', dest: '/opt/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz' }

- name: Extract Zookeeper to {{ zookeeper_install_dir }}
  include_tasks: ../../common/tasks/unarchive.yml
  vars:
    extract_files:
      - { src: '/opt/apache-zookeeper-{{ zookeeper_version }}-bin.tar.gz', dest: '{{ zookeeper_install_dir }}' }

- name: Set Zookeeper Install Dir
  include_tasks: ../../common/tasks/chown.yml
  vars:
    chown_dirs:
      - "{{ zookeeper_install_dir }}"

- name: Render Zookeeper Conf
  include_tasks: ../../common/tasks/render_conf.yml
  vars:
    render_files:
      - { src: 'zoo.cfg.j2', dest: '{{ zookeeper_conf_file }}' }
      - { src: 'zookeeper.service.j2', dest: '/etc/systemd/system/zookeeper.service' }

- name: Write myid file
  lineinfile:
    path: "{{ zookeeper_myid_file }}"
    line: '{{ myid }}'
    state: present
    create: yes

- name: Make myid file
  file:
    path: "{{ zookeeper_myid_file }}"
    owner: hadoop
    group: hadoop

- name: Start Zookeeper
  include_tasks: ../../common/tasks/start.yml
  vars:
    services:
      - "zookeeper"
